<a href="https://colab.research.google.com/github/jaekyoungkim/DLMLwithTorch/blob/main/pytorch%EB%A5%BC_%ED%99%9C%EC%9A%A9%ED%95%9C_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D%2C_%EB%94%A5%EB%9F%AC%EB%8B%9D_%EC%B2%A0%EC%A0%80%EC%9E%85%EB%AC%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1부 우리 일상속의 AI

In [ ]:
# 라이브러리 설치

In [ ]:
conda install pytorch torchvision -c pytorch
conda install jupyter
conda install pillow
conda matplotliv
conda install pandas
conda install scikit-learn
#pip install konlpy

# 2부 머신러닝 입문 

In [ ]:
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
from torch.utils.data import DataLoader, TensorDataset

In [ ]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split

In [ ]:
import pandas as pd

In [ ]:
wine=load_wine()
wine

{'DESCR': '.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 178 (50 in each of three classes)\n    :Number of Attributes: 13 numeric, predictive attributes and the class\n    :Attribute Information:\n \t\t- Alcohol\n \t\t- Malic acid\n \t\t- Ash\n\t\t- Alcalinity of ash  \n \t\t- Magnesium\n\t\t- Total phenols\n \t\t- Flavanoids\n \t\t- Nonflavanoid phenols\n \t\t- Proanthocyanins\n\t\t- Color intensity\n \t\t- Hue\n \t\t- OD280/OD315 of diluted wines\n \t\t- Proline\n\n    - class:\n            - class_0\n            - class_1\n            - class_2\n\t\t\n    :Summary Statistics:\n    \n    ============================= ==== ===== ======= =====\n                                   Min   Max   Mean     SD\n    ============================= ==== ===== ======= =====\n    Alcohol:                      11.0  14.8    13.0   0.8\n    Malic Acid:                   0.74  5.80    2.34  1.12\n    Ash:           

In [ ]:
pd.DataFrame(wine.data, columns=wine.feature_names)

alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0      14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1      13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2      13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3      14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4      13.24        2.59  2.87  ...  1.04                          2.93    735.0
..       ...         ...   ...  ...   ...                           ...      ...
173    13.71        5.65  2.45  ...  0.64                          1.74    740.0
174    13.40        3.91  2.48  ...  0.70                          1.56    750.0
175    13.27        4.28  2.26  ...  0.59                          1.56    835.0
176    13.17        2.59  2.37  ...  0.60                          1.62    840.0
177    14.13        4.10  2.74  ...  0.61                          1.60    560.0

[178 rows x 13 columns]

In [ ]:
wine.data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [ ]:
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [ ]:
wine_data = wine.data[0:130]
wine_target = wine.target[0:130]
np.random.seed(100)
train_x, test_x, train_y, test_y = train_test_split(wine_data, wine_target, test_size = 0.2)
print(len(train_x))
print(len(test_x))
print(train_x)
print(train_y)


104
26
[[1.339e+01 1.770e+00 2.620e+00 ... 9.200e-01 3.220e+00 1.195e+03]
 [1.229e+01 1.410e+00 1.980e+00 ... 1.230e+00 2.740e+00 4.280e+02]
 [1.196e+01 1.090e+00 2.300e+00 ... 9.900e-01 3.130e+00 8.860e+02]
 ...
 [1.237e+01 1.170e+00 1.920e+00 ... 1.120e+00 3.480e+00 5.100e+02]
 [1.350e+01 1.810e+00 2.610e+00 ... 1.120e+00 3.820e+00 8.450e+02]
 [1.483e+01 1.640e+00 2.170e+00 ... 1.080e+00 2.850e+00 1.045e+03]]
[0 1 1 1 1 1 1 0 1 0 1 0 0 1 0 1 1 0 0 0 0 1 0 1 0 1 1 0 1 0 0 1 1 1 1 0 1
 1 0 1 1 1 1 0 0 0 0 1 1 0 0 1 1 1 0 1 1 1 0 1 1 1 0 0 0 1 1 1 1 1 0 0 0 0
 0 0 1 1 0 0 0 1 1 1 0 1 1 1 0 0 1 1 0 1 0 1 0 0 1 1 1 1 0 0]


In [ ]:
len(wine.target)

178

In [ ]:
train_x, test_x, train_y, test_y = train_test_split(wine_data, wine_target, test_size = 0.2)

In [ ]:
len(train_x)

104

In [ ]:
len(test_x)

26

In [ ]:
train_x = torch.from_numpy(train_x).float()

In [ ]:
train_y = torch.from_numpy(train_y).long()

In [ ]:
test_x = torch.from_numpy(test_x).float()

In [ ]:
test_y = torch.from_numpy(test_y).long()

In [ ]:
print(train_x.shape)

torch.Size([104, 13])


In [ ]:
print(train_y.shape)

torch.Size([104])


In [ ]:
#torch.from_numpy(ndarray) : numpy배열을 tensor로 변환

In [ ]:
train = TensorDataset(train_x, train_y)
print(train[0])

(tensor([1.3830e+01, 1.6500e+00, 2.6000e+00, 1.7200e+01, 9.4000e+01, 2.4500e+00,
        2.9900e+00, 2.2000e-01, 2.2900e+00, 5.6000e+00, 1.2400e+00, 3.3700e+00,
        1.2650e+03]), tensor(0))


In [ ]:
# 미니 배치로 분할
train_loader = DataLoader(train, batch_size=16, shuffle=True)

In [ ]:
train_loader

In [ ]:
# torch.utils.data.Dataloader(dataset, batch_size =1, shuffle=False)

In [ ]:
class Net(nn.Module):
  def __init__(self) :
    super(Net, self).__init__()
    self.fc1 = nn.Linear(13,96)
    self.fc2 = nn.Linear(96,2)
  def forward(self,x):
    x = F.relu(self.fc1(x))
    x = self.fc2(x)
    return F.log_softmax(x)
# 인스턴스 생성
model = Net()

In [ ]:
model

Net(
  (fc1): Linear(in_features=13, out_features=96, bias=True)
  (fc2): Linear(in_features=96, out_features=2, bias=True)
)

In [ ]:
 # 모형학습
criterion = nn.CrossEntropyLoss()
optimizer=optim.SGD(model.parameters(), lr=0.01)

In [ ]:
criterion

CrossEntropyLoss()

In [ ]:
for epoch in range(300):
  total_loss= 0 
  for train_x, train_y in train_loader:
    train_x , train_y = Variable(train_x), Variable(train_y)
    optimizer.zero_grad()
    output = model(train_x)
    loss=criterion(output, train_y) # 
    loss.backward()
    optimizer.step()
    total_loss += loss.data   # 책에 나온 내용 수정함  total_loss += loss.data[0]
  if (epoch+1) % 50 ==0:
    print(epoch+1, total_loss)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  if __name__ == '__main__':


50 tensor(4.8521)
100 tensor(4.8535)
150 tensor(4.8491)
200 tensor(4.8505)
250 tensor(4.8514)
300 tensor(4.8517)


In [ ]:
test_x, test_y = Variable(test_X), Variable(test_Y)
test_y

tensor([1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
        0, 1])

In [ ]:
result = torch.max(model(test_x).data, 1)[1]
result

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  if __name__ == '__main__':


tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1])

In [ ]:
test_x, test_y = Variable(test_x), Variable(test_y)

result = torch.max(model(test_x).data,1)[1]
result

tensor([0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0])

In [ ]:
test_y

tensor([0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
        1, 1])

In [ ]:
accuracy = sum(test_y.data.numpy() == result.numpy()) / len(test_y.data.numpy())
accuracy

0.6923076923076923

# 3부 딥러닝 

In [ ]:

class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        # 입력층
        self.fc1 = nn.Linear(13,96)
        #중간층
        self.fc2 = nn.Linear(96,96)
        self.fc3 = nn.Linear(96,96)
        self.fc4 = nn.Linear(96,96)
        self.fc5 = nn.Linear(96,96)
        #출력층
        self.fc6 = nn.Linear(96,2)
        
    def forward(self,x):
        #입력층~ 중간층(4층): 활성화 함순 relu 함수 사용
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        x = F.relu(self.fc4(x))
        x = F.relu(self.fc5(x))
        # 출력층
        x = self.fc6(x)
        #출력층 활성화 함수는 로그소프트맥스 함수 사용
        return F.log_softmax(x, dim = 1)
    
# 인스턴스 생성
model= Net()    

In [ ]:
model

Net(
  (fc1): Linear(in_features=13, out_features=96, bias=True)
  (fc2): Linear(in_features=96, out_features=96, bias=True)
  (fc3): Linear(in_features=96, out_features=96, bias=True)
  (fc4): Linear(in_features=96, out_features=96, bias=True)
  (fc5): Linear(in_features=96, out_features=96, bias=True)
  (fc6): Linear(in_features=96, out_features=2, bias=True)
)

In [ ]:
# 오차함수 객체
criterion = nn.CrossEntropyLoss()

# 최적화를 담당할 객체
optimizer = optim.SGD(model.parameters(),lr =0.01)

In [ ]:
for epoch in range(300):
  total_loss= 0 
  for train_x, train_y in train_loader:
    train_x , train_y = Variable(train_x), Variable(train_y)
    optimizer.zero_grad()
    output = model(train_x)
    loss=criterion(output, train_y) 
    loss.backward()
    optimizer.step()
    total_loss += loss.data   # 책에 나온 내용 수정함  total_loss += loss.data[0]
  if (epoch+1) % 50 == 0:
      print(epoch+1,total_loss)

50 tensor(2.3669)
100 tensor(2.3115)
150 tensor(1.4328)
200 tensor(1.3084)
250 tensor(1.4490)
300 tensor(1.5422)


In [ ]:
#계산 그래프 구성
test_x, test_y = Variable(test_x), Variable(test_y)

# 출력이 0 또는 1이 되게함
result = torch.max(model(test_x).data, dim = 1)[1]

#모형의 정확도 측정
accuracy = sum(test_y.data.numpy() == result.numpy()) / len(test_y.data.numpy())
accuracy

0.8076923076923077